### ISSUE TITLE
Bug: Prettier vs. Eslint

### ISSUE THREAD

**Issue by MartinaVilimova** [out-fox-it/aj-ty-spojka#38]
Reproduction steps: 
- apply with-alpha-hex function on line 38
- run yarn code:fix
- run yarn code:check

![image](https://user-images.githubusercontent.com/58363173/105775457-1dbb0c80-5f67-11eb-88cc-4e7655e847e0.png)
Prettier throw error.

**Comment by macajind** [comment]
Fixed with commit 5aaa7ed in #37
