### ISSUE TITLE
Mobile menu or Form bug

### ISSUE THREAD

**Issue by agnes97** [out-fox-it/aj-ty-spojka#55]
### TRANSPARENCY
...when I open pages with Register or Login on iPhone5/SE or similar small phone...
![menuBug](https://user-images.githubusercontent.com/76131194/108074308-57b09780-7069-11eb-88e2-eaf4252ac3d9.png)
...when I scroll down...
![menuBug2](https://user-images.githubusercontent.com/76131194/108074307-57b09780-7069-11eb-8e57-b1e1751ba0e2.png)

So it might be the menu or it might be the form and I don't know. :thinking: ´

**Comment by MartinaVilimova** [comment]
I think this will be a menu error. but it's weird that the position fixed layer is down. Just try to put a z-index.
