### ISSUE TITLE
Global Styles

### ISSUE THREAD

**Issue by agnes97** [out-fox-it/aj-ty-spojka#58]
After merging contacts that also use a border style I'd like to make universal, I suggest adding these as global styles:

**Font** (this has it's own issue already since we also need to choose it) and **font sizes**

**StyledTitle** (H1 as used in all components)
**StyledBorder** (the border I used in Contacts, it's the same for Authors page and same that is used for Buttons)
**StyledLink** (it was also used several times already and it's mostly the same)

**StyledWrapper** (and perhaps Wrapper in some way as it's often grid with the same centering styles)

Please, comment any other styles we repeat often, I'm sure we could benefit from making them global. :3 

--> define **enum** for media-queries!

**Comment by MartinaVilimova** [comment]
StyledWrapper is a great idea 👍 at least we would stick to the same size. Other than colors, I can't think of anything else yet.
