### ISSUE TITLE
[CALL 14. 03.] Matching

### ISSUE THREAD

**Issue by MartinaVilimova** [out-fox-it/aj-ty-spojka#87]
### Matching co zatím máme 😂
![image](https://user-images.githubusercontent.com/58363173/110788813-66a4f700-826f-11eb-88e9-27bd986314c1.png)

**Každý může sem připsat co ho napadá k tomuto tématu. Pak se to pokusíme vyřešit u diskuze:**
- Chceme pod tlačítky nějaký návod nebo hned hledání?
- Po kliknutí na tlačítko se zobrazí filtr k vybranému hledání (mentor/mentee/buddy) nebo po kliknutí se přesměrujeme na jinou stránku s hledáním?
- Pokud bude profil propojen s matchingem co budeme z profilu brát a co budeme do matchingu dopisovat (většinu informací bude asi na profilu, ale problém s taháním a tříděním dat, uživatelé by si museli dávat velký pozor na to co kam vyplňují, za to ve filtru při matchingu to asi bude mnohem přehlednější, ale bude asi méně podnětů k vyhledání těch správných kontaktů)?
- Hledání bude zapnuté pořád nebo lze to nastavit na jak dlouho?
- Budeme regulovat počet emailů a jestli ano tak kolik?
- Budeme regulovat počet vyhledaných kontaktů a jestli ano tak kolik?
- Též je dobré se zamyslet zda se vyhledaný počet kontaktů na den bude přičítat k jinému dni nebo se vždy promaže a budeme mít jen viditelných pár kontaktů. První den 5 nových kontaktů, 7 den 35 kontaktů v seznamu nebo jen 5?

**Comment by agnes97** [comment]
**Přidala bych:** 
- 100% stručné, ale jasné popisy. Je to nejdůležitější stránka webu, tak možná i tutoriál.
- tlačítka bych vložila "doprostřed" matching formuláře (nad nimi, co mají dělat, pod nimi políčka na vyplnění nebo tak něco)
- matching formulář určitě formou univerzálního Form componentu

- matching by měl být časově ohraničený 

Třeba pro nieche technologie, kde uživatel očekává, že se mu ozve málo lidí, nemůže pořád kontrolovat stránku,. Místo toho čeká na e-mail, který mu přijde třeba po půl roce od zadání dlouhodobého matchingu. Nejefektivnější by asi bylo, kdyby si uživatel sám určil, jak dlouho chce, aby mu matching běžel (s možnostmi jako "dokud ho nezruším", "měsíc", "6 měsíců" - pro nás z businessového pohledu čím delší matchingy, tím více uživatelů, kteří se můžou propojit). Plus možnost "jednorázového" matchingu, který najde všechny kontakty, které jsou aktuálně k dispozici, a žádné e-maily mu už nechodí.

**Poznámky:**
- stojím si za tím, že profil s matchingem nemůže být propojený, protože na profilu jsou úplně jiné informace (co jsem dělala nemusí být to, co hledám) - matching by podle mě měl propojovat POUZE s jinými aktivními matchingy, nikoli se všemi profily uživatelů

- regulování počtu možných spojení určitě ano, ale otázka je jak. :thinking: 

Dobře mi zní třeba 5 denně (pak by tam vždy muselo být dopsáno, že "zítra" bude mít uživatel k dispozici dalších 5 uživatelů), ale je otázka, jak dobře to půjde zařídit po technické stránce. Tohle nám doporučovala i Anička, podobně to dělají různé seznamky, aby lidé nebyli přetížení množstvím možností a často se vraceli.

- regulování počtu e-mailů

To zní logicky! Otázka je, jestli to uděláme v matchingu nebo v profilu nebo pro jistotu v obojím. Každopádně si to představuju jako klikací možnosti "Pošlete mi e-mail: max. 1x denně, max. 1x týdně, pro každou novou žádost o spojení" (Pro zprávy e-maily posílat nepotřebujeme, o kontaktu, se kterým komunikuješ, už víš, nevíš o nové žádosti, kterou ti někdo poslal, nebo o schválení tvojí žádosti někomu jinému.)

**Comment by tomas90hampl** [comment]
Vyřešení otázek:

- Chceme pod tlačítky nějaký návod nebo hned hledání?
  - Ano ale bude se to řešit až při konkrétní implementaci, možná přibude nějaké videjko v nějaké sekci nápověda.
- Po kliknutí na tlačítko se zobrazí filtr k vybranému hledání (mentor/mentee/buddy) nebo po kliknutí se přesměrujeme na jinou stránku s hledáním?
   - Přesměruje se na novou stránku, kde budou záložky mentor/mentee/buddy). Každá tato záložka bude postránka
- Pokud bude profil propojen s matchingem co budeme z profilu brát a co budeme do matchingu dopisovat (většinu informací bude asi na profilu, ale problém s taháním a tříděním dat, uživatelé by si museli dávat velký pozor na to co kam vyplňují, za to ve filtru při matchingu to asi bude mnohem přehlednější, ale bude asi méně podnětů k vyhledání těch správných kontaktů)?
  - Propojení bude záviset hlavně na informaci, které vyplníme v matchingu. INformace z profilu budou sloužit jako doplněk a bude se podle nich například řadit, ale určitě neovlivní to, jestli se nám daný člověk ukáže v seznamu lidí.
- Hledání bude zapnuté pořád nebo lze to nastavit na jak dlouho?
  - Ano pořád bude zapnuté, dokud ho nevypneme.
- Budeme regulovat počet emailů a jestli ano tak kolik?
  - Emaily zatím neřešíme
- Budeme regulovat počet vyhledaných kontaktů a jestli ano tak kolik?
  - Zatím neomezeně
- Též je dobré se zamyslet zda se vyhledaný počet kontaktů na den bude přičítat k jinému dni nebo se vždy promaže a budeme mít jen viditelných pár kontaktů. První den 5 nových kontaktů, 7 den 35 kontaktů v seznamu nebo jen 5?
  - Zatím neřešíme
